d1 = {"apple", "banana", "cherry","mango","grape"}
d2 = {"kiwi", "orange", "mango","pear","grape"}
print("the original basket of fruits is:",d1)
print("the second basket of fruits is:",d2)
d1.add("orange")
print("the updated basket of fruits is:",d1)
cf = d1.intersection(d2)
print("the common fruits in both baskets are:",cf)
import array as arr
fc = arr.array('i', [3,5,9])
fc.insert(1, 7)
fc.append(11)
print("the updated fruit count is:",fc)
c4 = fc.count(5)
print("the count of fruit 5 is:",c4)
fc.reverse()
print("the reversed fruit count is:",fc)
print("")
print("====FRUIT BASKET ORGANISER====")
print("basket of fruits is:",d1)
print("second basket of fruits is:",d2)
print("the common fruits in both baskets are:",cf)
print("the updated fruit count is:",fc)
print("==================================")
